name: Release
on:
  push:
    tags:
      - '*'
  pull_request:
jobs:
  build:
    name: Release for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            name: linux64
            artifact_name: target/release/icx-asset
            asset_name: icx-asset-linux64
          - os: macos-12
            name: macos
            artifact_name: target/release/icx-asset
            asset_name: icx-asset-macos
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: |
          cd src/canisters/frontend/icx-asset
          cargo build --release --locked
      - name: 'Upload assets'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
          retention-days: 3
  test:
    needs: build
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            asset_name: icx-asset-linux64
          - os: ubuntu-20.04
            asset_name: icx-asset-linux64
          - os: macos-13
            asset_name: icx-asset-macos
          - os: macos-12
            asset_name: icx-asset-macos
    steps:
      - name: Get executable
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
      - name: Executable runs
        run: |
          chmod +x icx-asset
          ./icx-asset --version
  publish:
    needs: test
    name: Publish ${{ matrix.asset_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - asset_name: icx-asset-linux64
          - asset_name: icx-asset-macos
    runs-on: ubuntu-latest
    steps:
      - name: Get executable
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: icx-asset
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
